# 日志配置
logging:
  level:
    root: info
    com.domain.food: debug

#spring 文件上传配置
spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 15MB

# 业务数据配置
business:
  web:
    showStack: false
    imagePath: file:c:/food/image
  db:
    interval: 5
    expireTime: 10
    path: file:c:/food/db