# 日志配置
logging:
  level:
    root: info
    com.domain.food: debug

# 业务数据配置
business:
  web:
    showStack: false
    imagePath: file:c:/food/image
  db:
    interval: 1
    expireTime: 1
    path: file:c:/food/db